### ISSUE TITLE
All Messages Are Zero Bytes

### ISSUE THREAD

**Issue by chrisc30** [HaikuArchives/Beam#26]
I added my IMAP iCloud account and it can see the IMAP folder structure and will attempt to download the messages in the folders but they are all 0 bytes and Beam error log keeps complaining:Could not find any header-fields in this header

**Comment by nx6-archived** [comment]
I might have a solution for this issue. Beam sends `UID FETCH xxid rfc822` but iCloud returns an empty response to it.
Providing `UID FETCH xxid body[]` solves the problem. Before I can submit a patch, I need to do some tests with other providers to avod intreducing a regression
