### ISSUE TITLE
Fix x86_64 build

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Beam#5]
Now that we have a working liblayout.so package for x86_64 it would be great for Beam to follow.

**Comment by diversys** [comment]
@waddlesplash want to give it a go?

**Comment by waddlesplash** [comment]
very busy with other stuff right now...

**Comment by diversys** [comment]
@janus2 wanna take a look? :)

**Comment by korli** [comment]
added a patch for beam, see https://github.com/haikuports/haikuports/commit/5841f628860f3a9b57e5d9b931353fd781d602a0 
but liblayout is broken (https://github.com/diversys/liblayout/issues/4)

**Comment by korli** [comment]
PR https://github.com/HaikuArchives/Beam/pull/8

**Comment by diversys** [comment]
Fixed in 904926d022ff363dd17e208215bb53d65d7e91be.
